name: Mirror to Codeberg

on:
  push:
    branches: [master]
    tags: ['*']

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to Codeberg
        env:
          CODEBERG_TOKEN: ${{ secrets.CODEBERG_TOKEN }}
        run: |
          git remote add codeberg "https://flintwave:${CODEBERG_TOKEN}@codeberg.org/flintwaveradio/flintwave-kdh-flasher.git"
          git push codeberg --all --force
          git push codeberg --tags --force
